# Site settings
title: "*fukaoi.org"
email: you@example.com
description: > # this means to ignore newlines until "baseurl:"
  A simple, whitespace, helvetica based portfolio theme.
baseurl:  # the subpatdh of your site, e.g. /blog/
url:  http://fukaoi.org
twitter_username: fukaoi
github_username:  fukaoi

# Build settings
markdown: kramdown

# Pagination
gems: [jekyll-paginate]
paginate: 5
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  poetry:
    output: true
    permalink: /poetry/:path/
